name: C/C++ CI

on:
  push:
    branches: [ master, cSpec ]
  pull_request:
    branches: [ master, cSpec ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        git clone https://github.com/mumuki/cspec.git
        cd cspec
        make
        make install
    - name: make
      run: make clean
    - name: make all
      run: make all
    - name: run tests
      run: ./eg-alumnos-c