name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install cppunit
      run: sudo apt install -y libcunit1 libcunit1-doc libcunit1-dev
      - name: make
      run: make clean
      - name: make all
      run: make all
      - name: run tests
      run: ./eg-alumnos-c