name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install lcov
      run: sudo apt-get update && sudo apt-get install -y lcov

    - name: Install cSpec
      run: |
        git clone https://github.com/mumuki/cspec.git /tmp/cspec
        cd /tmp/cspec
        make
        sudo make install
        sudo ldconfig

    - name: Compilar demo
      run: make

    - name: Correr tests
      run: make test

    - name: Generar reporte de cobertura
      run: make coverage

    - name: Subir cobertura a Codecov
      uses: codecov/codecov-action@v4
      with:
        files: build/lcov.info
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
